name: Arch Linux

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  arch:
    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          sudo pacman -Syu --noconfirm wget git openmp base-devel bc zip
          git clone --depth=1 https://github.com/jhuny-arj/android_kernel_realme_RM6785.git  -b full-lto
          cd android_kernel_realme_RM6785
          bash build.sh
